import { describe, expect, test } from "bun:test";
import { isAgentAttribution } from "./lifecycle";

describe("isAgentAttribution", () => {
  test("detects known attribution subjects", () => {
    expect(isAgentAttribution("Generated by [Cursor](https://cursor.com)")).toBe(true);
    expect(isAgentAttribution("  🤖 Generated with [Claude Code](https://claude.ai/code)")).toBe(true);
  });

  test("allows normal subjects", () => {
    expect(isAgentAttribution("feat: add feature")).toBe(false);
    expect(isAgentAttribution("Also Generated by [Cursor] in the middle")).toBe(false);
  });
});
