import { afterEach, describe, expect, test } from "bun:test";
import { existsSync, mkdtempSync, readFileSync, rmSync, statSync, writeFileSync } from "fs";
import { join } from "path";
import { tmpdir } from "os";
import { installCommitMsgHook, isAgentAttribution } from "./lifecycle";

describe("installCommitMsgHook", () => {
  const created: string[] = [];

  afterEach(() => {
    for (const dir of created.splice(0)) {
      try {
        rmSync(dir, { recursive: true, force: true });
      } catch { /* ignore */ }
    }
  });

  test("creates hooks directory and commit-msg script", () => {
    const id = `test-${crypto.randomUUID()}`;
    const hooksPath = installCommitMsgHook(id);
    created.push(hooksPath);

    expect(existsSync(hooksPath)).toBe(true);
    const scriptPath = join(hooksPath, "commit-msg");
    expect(existsSync(scriptPath)).toBe(true);
    const content = readFileSync(scriptPath, "utf-8");
    expect(content).toContain("#!/bin/sh");
    expect(content).toContain("Strip agent CLI attribution");
    expect(content).toContain("grep -v -E");
  });

  test("commit-msg is executable", () => {
    const id = `test-${crypto.randomUUID()}`;
    const hooksPath = installCommitMsgHook(id);
    created.push(hooksPath);

    const mode = statSync(join(hooksPath, "commit-msg")).mode;
    expect(mode & 0o111).not.toBe(0);
  });

  test("hook strips Cursor attribution lines", () => {
    const id = `test-${crypto.randomUUID()}`;
    const hooksPath = installCommitMsgHook(id);
    created.push(hooksPath);

    const dir = mkdtempSync(join(tmpdir(), "yk-hook-"));
    created.push(dir);
    const msgFile = join(dir, "COMMIT_EDITMSG");
    writeFileSync(
      msgFile,
      "feat: do something\n\nGenerated by [Cursor](https://cursor.com)\n",
      "utf-8",
    );

    const proc = Bun.spawnSync(["sh", join(hooksPath, "commit-msg"), msgFile], {
      timeout: 5000,
    });
    expect(proc.exitCode).toBe(0);
    expect(readFileSync(msgFile, "utf-8")).toBe("feat: do something\n");
  });

  test("hook strips Claude Code attribution lines", () => {
    const id = `test-${crypto.randomUUID()}`;
    const hooksPath = installCommitMsgHook(id);
    created.push(hooksPath);

    const dir = mkdtempSync(join(tmpdir(), "yk-hook-"));
    created.push(dir);
    const msgFile = join(dir, "COMMIT_EDITMSG");
    writeFileSync(
      msgFile,
      "fix: bug\n\n🤖 Generated with [Claude Code](https://claude.ai/code)\n",
      "utf-8",
    );

    const proc = Bun.spawnSync(["sh", join(hooksPath, "commit-msg"), msgFile], {
      timeout: 5000,
    });
    expect(proc.exitCode).toBe(0);
    expect(readFileSync(msgFile, "utf-8")).toBe("fix: bug\n");
  });

  test("hook preserves non-attribution lines", () => {
    const id = `test-${crypto.randomUUID()}`;
    const hooksPath = installCommitMsgHook(id);
    created.push(hooksPath);

    const dir = mkdtempSync(join(tmpdir(), "yk-hook-"));
    created.push(dir);
    const msgFile = join(dir, "COMMIT_EDITMSG");
    const body = "feat: title\n\nDetails here.\nAlso Generated by [Cursor] in prose is kept.\n";
    writeFileSync(msgFile, body, "utf-8");

    const proc = Bun.spawnSync(["sh", join(hooksPath, "commit-msg"), msgFile], {
      timeout: 5000,
    });
    expect(proc.exitCode).toBe(0);
    expect(readFileSync(msgFile, "utf-8")).toBe(body);
  });

  test("hook removes trailing blank lines after stripping attribution", () => {
    const id = `test-${crypto.randomUUID()}`;
    const hooksPath = installCommitMsgHook(id);
    created.push(hooksPath);

    const dir = mkdtempSync(join(tmpdir(), "yk-hook-"));
    created.push(dir);
    const msgFile = join(dir, "COMMIT_EDITMSG");
    writeFileSync(
      msgFile,
      "chore: x\n\nGenerated by [Cursor](https://cursor.com)\n\n\n",
      "utf-8",
    );

    const proc = Bun.spawnSync(["sh", join(hooksPath, "commit-msg"), msgFile], {
      timeout: 5000,
    });
    expect(proc.exitCode).toBe(0);
    expect(readFileSync(msgFile, "utf-8")).toBe("chore: x\n");
  });
});

describe("isAgentAttribution", () => {
  test("detects known attribution subjects", () => {
    expect(isAgentAttribution("Generated by [Cursor](https://cursor.com)")).toBe(true);
    expect(isAgentAttribution("  🤖 Generated with [Claude Code](https://claude.ai/code)")).toBe(true);
  });

  test("allows normal subjects", () => {
    expect(isAgentAttribution("feat: add feature")).toBe(false);
    expect(isAgentAttribution("Also Generated by [Cursor] in the middle")).toBe(false);
  });
});
