import { describe, test, expect, spyOn, afterEach, beforeEach } from "bun:test";
import { performLocalMerge, pushBaseBranch } from "./lifecycle";
import { cleanGitEnv } from "./worktree-manager";
import { mkdtemp, rm } from "fs/promises";
import { tmpdir } from "os";
import { join } from "path";

describe("performLocalMerge", () => {
  afterEach(() => {
    spyOn(Bun, "spawnSync").mockRestore();
  });

  const wt = {
    worktreePath: "/tmp/wt",
    baseBranch: "main",
    branchName: "yes-kanban/proj/T-1",
    repoPath: "/tmp/repo",
    repoId: "repo1",
  } as any;

  test("succeeds with squash merge", () => {
    const calls: string[][] = [];
    let commitMessage: string | undefined;

    spyOn(Bun, "spawnSync").mockImplementation((cmd: any) => {
      const args = Array.isArray(cmd) ? cmd.map(String) : [];
      calls.push(args);

      if (args.includes("commit") && args.includes("-m")) {
        const mIdx = args.indexOf("-m");
        commitMessage = args[mIdx + 1];
        return { exitCode: 0, stdout: Buffer.from(""), stderr: Buffer.from("") } as any;
      }
      if (args.includes("diff") && args.includes("--cached") && args.includes("--quiet")) {
        return { exitCode: 1, stdout: Buffer.from(""), stderr: Buffer.from("") } as any;
      }
      if (args.includes("log") && args.includes("--pretty=format:%s")) {
        return {
          exitCode: 0,
          stdout: Buffer.from("first change\nsecond change"),
          stderr: Buffer.from(""),
        } as any;
      }
      return { exitCode: 0, stdout: Buffer.from(""), stderr: Buffer.from("") } as any;
    });

    const result = performLocalMerge([wt]);

    expect(result.success).toBe(true);
    expect(calls.some(c => c.includes("checkout") && c.includes("main"))).toBe(true);
    expect(calls.some(c => c.includes("merge") && c.includes("--squash") && c.includes("yes-kanban/proj/T-1"))).toBe(
      true,
    );
    expect(calls.some(c => c.includes("log") && c.includes("main..yes-kanban/proj/T-1"))).toBe(true);
    expect(commitMessage).toBe("first change\n\nsecond change\n\nGenerated-by: Yes Kanban");
    expect(calls.some(c => c.includes("branch") && c.includes("-d"))).toBe(false);
  });

  test("filters agent attribution lines from squash commit message (E2E--200)", () => {
    let commitMessage: string | undefined;

    spyOn(Bun, "spawnSync").mockImplementation((cmd: any) => {
      const args = Array.isArray(cmd) ? cmd.map(String) : [];
      if (args.includes("commit") && args.includes("-m")) {
        const mIdx = args.indexOf("-m");
        commitMessage = args[mIdx + 1];
        return { exitCode: 0, stdout: Buffer.from(""), stderr: Buffer.from("") } as any;
      }
      if (args.includes("diff") && args.includes("--cached") && args.includes("--quiet")) {
        return { exitCode: 1, stdout: Buffer.from(""), stderr: Buffer.from("") } as any;
      }
      if (args.includes("log") && args.includes("--pretty=format:%s")) {
        return {
          exitCode: 0,
          stdout: Buffer.from(
            "real work\nGenerated by [Cursor](https://cursor.com)\n🤖 Generated with [Claude Code](https://claude.ai/code)",
          ),
          stderr: Buffer.from(""),
        } as any;
      }
      return { exitCode: 0, stdout: Buffer.from(""), stderr: Buffer.from("") } as any;
    });

    const result = performLocalMerge([wt]);

    expect(result.success).toBe(true);
    expect(commitMessage).toBe("real work\n\nGenerated-by: Yes Kanban");
  });

  test("single commit branch uses subject only (no body)", () => {
    let commitMessage: string | undefined;

    spyOn(Bun, "spawnSync").mockImplementation((cmd: any) => {
      const args = Array.isArray(cmd) ? cmd.map(String) : [];
      if (args.includes("commit") && args.includes("-m")) {
        const mIdx = args.indexOf("-m");
        commitMessage = args[mIdx + 1];
        return { exitCode: 0, stdout: Buffer.from(""), stderr: Buffer.from("") } as any;
      }
      if (args.includes("diff") && args.includes("--cached") && args.includes("--quiet")) {
        return { exitCode: 1, stdout: Buffer.from(""), stderr: Buffer.from("") } as any;
      }
      if (args.includes("log") && args.includes("--pretty=format:%s")) {
        return { exitCode: 0, stdout: Buffer.from("only change"), stderr: Buffer.from("") } as any;
      }
      return { exitCode: 0, stdout: Buffer.from(""), stderr: Buffer.from("") } as any;
    });

    const result = performLocalMerge([wt]);

    expect(result.success).toBe(true);
    expect(commitMessage).toBe("only change\n\nGenerated-by: Yes Kanban");
  });

  test("fails when checkout fails", () => {
    spyOn(Bun, "spawnSync").mockImplementation((cmd: any) => {
      const args = Array.isArray(cmd) ? cmd : [];
      if (args.includes("checkout")) {
        return { exitCode: 1, stdout: Buffer.from(""), stderr: Buffer.from("error: pathspec") } as any;
      }
      return { exitCode: 0, stdout: Buffer.from(""), stderr: Buffer.from("") } as any;
    });

    const result = performLocalMerge([wt]);

    expect(result.success).toBe(false);
    expect(result.error).toBeDefined();
  });

  test("cleans up on squash merge failure", () => {
    const calls: string[][] = [];

    spyOn(Bun, "spawnSync").mockImplementation((cmd: any) => {
      const args = Array.isArray(cmd) ? cmd.map(String) : [];
      calls.push(args);
      if (args.includes("merge") && args.includes("--squash")) {
        return { exitCode: 1, stdout: Buffer.from(""), stderr: Buffer.from("CONFLICT") } as any;
      }
      return { exitCode: 0, stdout: Buffer.from(""), stderr: Buffer.from("") } as any;
    });

    const result = performLocalMerge([wt]);

    expect(result.success).toBe(false);
    expect(result.error).toContain("squash merge failed");
    const squashIdx = calls.findIndex(c => c.includes("merge") && c.includes("--squash"));
    expect(squashIdx).toBeGreaterThanOrEqual(0);
    const afterSquash = calls.slice(squashIdx + 1);
    expect(afterSquash.some(c => c.includes("reset") && c.includes("--hard") && c.includes("HEAD"))).toBe(true);
  });

  test("cleans up when commit fails after squash", () => {
    const calls: string[][] = [];

    spyOn(Bun, "spawnSync").mockImplementation((cmd: any) => {
      const args = Array.isArray(cmd) ? cmd.map(String) : [];
      calls.push(args);
      if (args.includes("commit") && args.includes("-m")) {
        return { exitCode: 1, stdout: Buffer.from(""), stderr: Buffer.from("identity unknown") } as any;
      }
      if (args.includes("diff") && args.includes("--cached") && args.includes("--quiet")) {
        return { exitCode: 1, stdout: Buffer.from(""), stderr: Buffer.from("") } as any;
      }
      if (args.includes("log") && args.includes("--pretty=format:%s")) {
        return { exitCode: 0, stdout: Buffer.from("a\nb"), stderr: Buffer.from("") } as any;
      }
      return { exitCode: 0, stdout: Buffer.from(""), stderr: Buffer.from("") } as any;
    });

    const result = performLocalMerge([wt]);

    expect(result.success).toBe(false);
    expect(result.error).toContain("commit failed");
    const commitIdx = calls.findIndex(c => c.includes("commit") && c.includes("-m"));
    expect(commitIdx).toBeGreaterThanOrEqual(0);
    const afterCommit = calls.slice(commitIdx + 1);
    expect(afterCommit.some(c => c.includes("reset") && c.includes("--hard") && c.includes("HEAD"))).toBe(true);
  });

  test("cleans up when git log fails after squash", () => {
    const calls: string[][] = [];

    spyOn(Bun, "spawnSync").mockImplementation((cmd: any) => {
      const args = Array.isArray(cmd) ? cmd.map(String) : [];
      calls.push(args);
      if (args.includes("log") && args.includes("--pretty=format:%s")) {
        return { exitCode: 1, stdout: Buffer.from(""), stderr: Buffer.from("bad revision") } as any;
      }
      if (args.includes("diff") && args.includes("--cached") && args.includes("--quiet")) {
        return { exitCode: 1, stdout: Buffer.from(""), stderr: Buffer.from("") } as any;
      }
      return { exitCode: 0, stdout: Buffer.from(""), stderr: Buffer.from("") } as any;
    });

    const result = performLocalMerge([wt]);

    expect(result.success).toBe(false);
    expect(result.error).toContain("failed to collect commit messages");
    const logIdx = calls.findIndex(c => c.includes("log") && c.includes("--pretty=format:%s"));
    expect(logIdx).toBeGreaterThanOrEqual(0);
    const afterLog = calls.slice(logIdx + 1);
    expect(afterLog.some(c => c.includes("reset") && c.includes("--hard") && c.includes("HEAD"))).toBe(true);
  });

  test("skips when squash produces no changes (idempotency)", () => {
    const commitCalls: string[][] = [];

    spyOn(Bun, "spawnSync").mockImplementation((cmd: any) => {
      const args = Array.isArray(cmd) ? cmd.map(String) : [];
      if (args.includes("commit")) {
        commitCalls.push(args);
      }
      if (args.includes("diff") && args.includes("--cached") && args.includes("--quiet")) {
        return { exitCode: 0, stdout: Buffer.from(""), stderr: Buffer.from("") } as any;
      }
      return { exitCode: 0, stdout: Buffer.from(""), stderr: Buffer.from("") } as any;
    });

    const result = performLocalMerge([wt]);

    expect(result.success).toBe(true);
    expect(commitCalls.length).toBe(0);
  });

  test("merges multiple worktrees independently", () => {
    const wt2 = {
      ...wt,
      repoPath: "/tmp/repo2",
      branchName: "yes-kanban/proj/T-2",
    };

    const squashedBranches: string[] = [];
    spyOn(Bun, "spawnSync").mockImplementation((cmd: any) => {
      const args = Array.isArray(cmd) ? cmd.map(String) : [];
      if (args.includes("merge") && args.includes("--squash")) {
        const branchIdx = args.indexOf("--squash") + 1;
        if (branchIdx > 0 && args[branchIdx]) squashedBranches.push(args[branchIdx]);
      }
      if (args.includes("diff") && args.includes("--cached") && args.includes("--quiet")) {
        return { exitCode: 0, stdout: Buffer.from(""), stderr: Buffer.from("") } as any;
      }
      return { exitCode: 0, stdout: Buffer.from(""), stderr: Buffer.from("") } as any;
    });

    const result = performLocalMerge([wt, wt2]);

    expect(result.success).toBe(true);
    expect(squashedBranches).toEqual(["yes-kanban/proj/T-1", "yes-kanban/proj/T-2"]);
  });

  test("stops on first failure with multiple worktrees", () => {
    const wt2 = { ...wt, repoPath: "/tmp/repo2", branchName: "yes-kanban/proj/T-2" };
    const squashRepos: string[] = [];

    spyOn(Bun, "spawnSync").mockImplementation((cmd: any) => {
      const args = Array.isArray(cmd) ? cmd.map(String) : [];
      if (args.includes("merge") && args.includes("--squash")) {
        const cIdx = args.indexOf("-C");
        const repo = cIdx >= 0 ? args[cIdx + 1] : "";
        squashRepos.push(repo ?? "");
        if (repo === "/tmp/repo") {
          return { exitCode: 1, stdout: Buffer.from(""), stderr: Buffer.from("CONFLICT") } as any;
        }
      }
      return { exitCode: 0, stdout: Buffer.from(""), stderr: Buffer.from("") } as any;
    });

    const result = performLocalMerge([wt, wt2]);

    expect(result.success).toBe(false);
    expect(squashRepos).toEqual(["/tmp/repo"]);
  });
});

describe("pushBaseBranch", () => {
  afterEach(() => {
    spyOn(Bun, "spawnSync").mockRestore();
  });

  const wt = {
    worktreePath: "/tmp/wt",
    baseBranch: "main",
    branchName: "yes-kanban/proj/T-1",
    repoPath: "/tmp/repo",
    repoId: "repo1",
  } as any;

  test("pushes each unique repoPath:baseBranch once", () => {
    const pushes: string[][] = [];
    spyOn(Bun, "spawnSync").mockImplementation((cmd: any) => {
      const args = Array.isArray(cmd) ? cmd.map(String) : [];
      if (args.includes("push") && args.includes("origin")) {
        pushes.push(args);
      }
      return { exitCode: 0, stdout: Buffer.from(""), stderr: Buffer.from("") } as any;
    });

    const result = pushBaseBranch([
      { ...wt, repoPath: "/a/r" },
      { ...wt, repoPath: "/a/r", branchName: "other" },
      { ...wt, repoPath: "/b/r" },
    ]);

    expect(result.success).toBe(true);
    expect(pushes.length).toBe(2);
  });

  test("returns error on push failure", () => {
    spyOn(Bun, "spawnSync").mockImplementation((cmd: any) => {
      const args = Array.isArray(cmd) ? cmd.map(String) : [];
      if (args.includes("push")) {
        return { exitCode: 1, stdout: Buffer.from(""), stderr: Buffer.from("no upstream") } as any;
      }
      return { exitCode: 0, stdout: Buffer.from(""), stderr: Buffer.from("") } as any;
    });

    const result = pushBaseBranch([wt]);
    expect(result.success).toBe(false);
    expect(result.error).toContain("push main failed for /tmp/repo");
  });

  test("attempts every distinct repo when an earlier push fails", () => {
    const pushes: string[][] = [];
    spyOn(Bun, "spawnSync").mockImplementation((cmd: any) => {
      const args = Array.isArray(cmd) ? cmd.map(String) : [];
      if (args.includes("push") && args.includes("origin")) {
        pushes.push(args);
        const cIdx = args.indexOf("-C");
        const repo = cIdx >= 0 ? args[cIdx + 1] : "";
        if (repo === "/a/r") {
          return { exitCode: 1, stdout: Buffer.from(""), stderr: Buffer.from("no upstream") } as any;
        }
      }
      return { exitCode: 0, stdout: Buffer.from(""), stderr: Buffer.from("") } as any;
    });

    const result = pushBaseBranch([
      { ...wt, repoPath: "/a/r" },
      { ...wt, repoPath: "/b/r" },
    ]);

    expect(pushes.length).toBe(2);
    expect(result.success).toBe(false);
    expect(result.error).toContain("/a/r");
    expect(result.error).toContain("no upstream");
  });

  test("aggregates errors when multiple distinct pushes fail", () => {
    spyOn(Bun, "spawnSync").mockImplementation((cmd: any) => {
      const args = Array.isArray(cmd) ? cmd.map(String) : [];
      if (args.includes("push")) {
        return { exitCode: 1, stdout: Buffer.from(""), stderr: Buffer.from("x") } as any;
      }
      return { exitCode: 0, stdout: Buffer.from(""), stderr: Buffer.from("") } as any;
    });

    const result = pushBaseBranch([
      { ...wt, repoPath: "/a/r" },
      { ...wt, repoPath: "/b/r" },
    ]);

    expect(result.success).toBe(false);
    expect(result.error).toContain("; ");
    expect(result.error).toContain("/a/r");
    expect(result.error).toContain("/b/r");
  });
});

describe("pushBaseBranch (integration)", () => {
  let tempDir: string;
  let barePath: string;
  let clientPath: string;

  beforeEach(async () => {
    tempDir = await mkdtemp(join(tmpdir(), "yk-push-"));
    barePath = join(tempDir, "origin.git");
    clientPath = join(tempDir, "client");
    const env = cleanGitEnv();
    Bun.spawnSync(["git", "init", "--bare", barePath], { env });
    Bun.spawnSync(["git", "init", clientPath], { env });
    Bun.spawnSync(["git", "-C", clientPath, "config", "user.email", "t@test.com"], { env });
    Bun.spawnSync(["git", "-C", clientPath, "config", "user.name", "T"], { env });
    Bun.spawnSync(["touch", join(clientPath, "README.md")], { env });
    Bun.spawnSync(["git", "-C", clientPath, "add", "."], { env });
    Bun.spawnSync(["git", "-C", clientPath, "commit", "-m", "init"], { env });
    Bun.spawnSync(["git", "-C", clientPath, "branch", "-M", "main"], { env });
    Bun.spawnSync(["git", "-C", clientPath, "remote", "add", "origin", barePath], { env });
    Bun.spawnSync(["git", "-C", clientPath, "push", "-u", "origin", "main"], { env });
    Bun.spawnSync(["sh", "-c", `echo more >> "${join(clientPath, "README.md")}"`], { env });
    Bun.spawnSync(["git", "-C", clientPath, "commit", "-am", "second", "--no-verify"], { env });
  });

  afterEach(async () => {
    await rm(tempDir, { recursive: true, force: true });
  });

  test("updates bare remote ref when local main is ahead", () => {
    const wt = {
      worktreePath: join(clientPath, "wt"),
      baseBranch: "main",
      branchName: "feature",
      repoPath: clientPath,
      repoId: "repo1",
    } as any;

    const beforeBare = Bun.spawnSync(
      ["git", "--git-dir", barePath, "rev-parse", "main"],
      { env: cleanGitEnv() },
    );
    const beforeLocal = Bun.spawnSync(
      ["git", "-C", clientPath, "rev-parse", "main"],
      { env: cleanGitEnv() },
    );
    expect(beforeBare.stdout.toString().trim()).not.toBe(beforeLocal.stdout.toString().trim());

    const result = pushBaseBranch([wt]);
    expect(result.success).toBe(true);

    const afterBare = Bun.spawnSync(
      ["git", "--git-dir", barePath, "rev-parse", "main"],
      { env: cleanGitEnv() },
    );
    const afterLocal = Bun.spawnSync(
      ["git", "-C", clientPath, "rev-parse", "main"],
      { env: cleanGitEnv() },
    );
    expect(afterBare.stdout.toString().trim()).toBe(afterLocal.stdout.toString().trim());
  });
});
